# Generated by Django 5.0 on 2023-12-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='social_extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='myuser',
            name='social_provider',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='myuser',
            name='social_uid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
